name: calculadora_imc
description: Calculadora de IMC
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.17.0 <3.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  material_symbols_icons: ^4.2873.0
  percent_indicator: ^4.2.3


dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  material_color_utilities: ^0.11.1
  meta: ^1.16.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/img/female.png
    - assets/img/male.png
  uses-material-design: true
